services:
  runner:
    image: myoung34/github-runner:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      RUNNER_SCOPE: repo
      RUNNER_NAME_PREFIX: myrunner
      LABELS: proto-runner-microservice
      REPO_URL: https://github.com/longlnOff/microservices-proto
      EPHEMERAL: 1
      ACCESS_TOKEN: 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
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.2'
          memory: 256M
